### PR TITLE
Switched color change from Kelvin to use Hue/Saturation for Home.app support

### PR DESCRIPTION
**Pull request by shoghicp**
Before you couldn't use Siri or Home.app to set the color/temperature of the lights, this change lets you do that. It also adds the ActiveState flag so you can see whether your lights are reachable by the IKEA bridge or not (for example, if they are turned off with the switch).

I think the code could be cleaned up a bit, but I wrote this yesterday and tested it for a while without issues (except lamps that don't support this, which I fixed)

Now you can say `Hey Siri, set the lights to red/blue/white/yellow` or change the color/temperature through different apps (which also support setting Kelvin through this interface).

 

This is partly based on an existing fork based on this code, then improved to support lights that don't handle color (big IKEA bulbs) and to display the current color as well.

EDIT: Now both Kelvin-based or Hue/Sat-based color changes work!

### CODE REVIEW

**Comment by stenehall** [comment]
This looks great! I'll have a look at it tonight.

**Comment by shoghicp** [comment]
I guess I will have to update my branch with the new changes, might do that later

**Comment by stenehall** [comment]
Have played around a bit with your PR, good job!  
Hower I'd much prefer if you could make this an option. Could you leave the Kelvin code in place and add this as a setting?. Add a setting in the config for Kelvin/Hue-Saturation.

While this works it also adds the RGB setting that just isn't correct for this types of lamps. It seems obvious that Ikea will release RGB lamps in the future so having it is for sure a good thing. But I'm not convinced everyone will prefer this over a Kelvin slider for the current lamps.

**Comment by shoghicp** [comment]
Yeah, right now I'm switching colors saying "red/white/yellow/blue" and that works. You can also go to the Temperature tab and switch it there. I think that both Kelvin and Hue/Sat based color changes can coexist at the same time, so I might end up doing that.

**Comment by shoghicp** [comment]
The new commit includes both kelvin and Hue/Saturation color changes. Both work at the same time, and you can use either to change it. In addition, I have removed the Kelvin characteristic from lamps that do not support setting the temperature (big IKEA bulbs with a single setting only).

For other testing stuff, I have almost every device in the IKEA line.

**Comment by stenehall** [comment]
This seems to work really nicely! Well done. Merging this now. The only thing I could find not working optimal were the sync between values. If you change kelvin the color isn't changed. If you change color kelvin's not changed. But that's for later :)

**Pull request merged**
